name: LIQUID 40 (derived from data_real)
symbols:
  - HDFCBANK
  - RELIANCE
  - ICICIBANK
  - ZOMATO
  - INFY
  - ETERNAL
  - BHARTIARTL
  - BSE
  - SBIN
  - TATAMOTORS
  - TCS
  - AXISBANK
  - KOTAKBANK
  - MAZDOCK
  - BAJFINANCE
  - HAL
  - M&M
  - LT
  - IDEA
  - BEL
  - WAAREEENER
  - ITC
  - JIOFIN
  - RVNL
  - MARUTI
  - SWIGGY
  - TATASTEEL
  - DIXON
  - INDIGO
  - IRFC
  - INDUSINDBK
  - TRENT
  - OLAELEC
  - COCHINSHIP
  - VEDL
  - PAYTM
  - NTPC
  - RECLTD
  - CDSL
  - ADANIENT
