name: NSE50 Liquid Auto
symbols:
  - HDFCBANK
  - RELIANCE
  - ICICIBANK
  - SBIN
  - INFY
  - BHARTIARTL
  - BSE
  - LT
  - SILVERBEES
  - ETERNAL
  - VEDL
  - TCS
  - M&M
  - AXISBANK
  - BAJFINANCE
  - MCX
  - GROWW
  - NETWEB
  - SHRIRAMFIN
  - KOTAKBANK
  - DIXON
  - ADANIPOWER
  - BEL
  - MARUTI
  - INDIGO
  - SUNPHARMA
  - TATASTEEL
  - WAAREEENER
  - GOLDBEES
  - ONGC
  - ITC
  - TEJASNET
  - HCLTECH
  - HAL
  - HINDALCO
  - HINDCOPPER
  - COALINDIA
  - KAYNES
  - BHEL
  - MAZDOCK
  - TMCV
  - NATIONALUM
  - GRSE
  - HINDUNILVR
  - EICHERMOT
  - IDEA
  - NTPC
  - JIOFIN
  - ADANIENT
  - POWERGRID
