backtest:
  name: paper_udiff_roll_liquid50_w2
  strategy: sma_crossover
  universe: nse50_liquid_auto
  start_date: "2026-02-24"
  end_date: "2026-03-10"
  exchange: NSE
  timeframe: 1d
  risk_profile: risk
  initial_capital: 500000
  close_all_at_end: true

strategy_params:
  fast_period: 2
  slow_period: 4
