backtest:
  name: paper_udiff_roll_w4
  strategy: sma_crossover
  universe: nifty50
  start_date: "2026-03-25"
  end_date: "2026-04-10"
  exchange: NSE
  timeframe: 1d
  risk_profile: risk
  initial_capital: 500000
  close_all_at_end: true

strategy_params:
  fast_period: 2
  slow_period: 4
